name: Deploy
env:
  TEST_VAR: true
on:
  workflow_dispatch:
    inputs:
      wordpress_archive:
        description: 'wordpress static site archive'
        required: true
jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Building
        shell: bash
        run: |
          echo $WORDPRESS_ARCHIVE
          echo "Built"

  confirm-deploy:
    name: Confirm deploy
    runs-on: ubuntu-latest
    needs: build
    environment: confirm-deploy
    steps:
      - name: Confirmed Deployment
        run: |
          echo "Confirmed"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: confirm-deploy
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deployed"
